name: Build

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        configuration: [ 'Debug', 'Release' ]
    env:
      APP_NAME: AuthenticatorHook

    steps:
      - uses: actions/checkout@v7

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build with Gradle Wrapper
        run: ./gradlew assemble${{ matrix.configuration }} --no-daemon

      # https://github.com/parallelcc/MixFlipMod/blob/main/.github/workflows/ci_build.yml
      - name: Set NAME_SUFFIX
        id: set-name-suffix
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            echo "NAME_SUFFIX=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            sha="${{ github.sha }}"
            sha_short="${sha:0:7}"
            echo "NAME_SUFFIX=$sha_short" >> $GITHUB_OUTPUT
          fi

      - name: Get and store apk path
        id: get-apk-path
        run: |
          set -o pipefail
          apk_path=$(find ./build/outputs/apk -name "*.apk" | head -n 1)
          new_path=$(echo "$apk_path" | sed 's/\.apk/-${{ steps.set-name-suffix.outputs.NAME_SUFFIX }}.unsigned.apk/g')
          mv "$apk_path" "$new_path"
          echo "APK_PATH=$new_path" >> $GITHUB_OUTPUT

      - name: Upload APK artifact
        uses: actions/upload-artifact@v7
        with:
          path: ${{ steps.get-apk-path.outputs.APK_PATH }}
          archive: false

  # dependency-submission:

  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write

  #   steps:
  #   - uses: actions/checkout@v7
  #   - name: Set up JDK 17
  #     uses: actions/setup-java@v5
  #     with:
  #       java-version: '17'
  #       distribution: 'temurin'

  #   # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
  #   # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
  #   - name: Generate and submit dependency graph
  #     uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
